version: "3.5"
services:

  spark-master:
    container_name: spark-master
    image: elopezdelara/miniconda3-spark:latest
    expose:
      - "8080"
    ports:
      - "8080:8080"
    command:
      - start-master.sh
    environment:
      - SPARK_NO_DAEMONIZE=1
      - SPARK_PUBLIC_DNS=localhost
    networks:
      - spark-cluster 
    volumes:
      - ./events:/tmp/spark-events

  spark-worker:
    depends_on:
      - spark-master
    image: elopezdelara/miniconda3-spark:latest
    expose:
      - "8081"
    ports: 
      - "8081:8081"
    command:
      - start-slave.sh
      - spark://spark-master:7077
    environment:
      - SPARK_NO_DAEMONIZE=1
      - SPARK_PUBLIC_DNS=localhost
    networks:
      - spark-cluster
    volumes:
      - ./events:/tmp/spark-events

  spark-history:
    depends_on:
      - spark-master
    container_name: spark-history
    image: elopezdelara/miniconda3-spark:latest
    expose:
      - "18080"
    ports:
      - "18080:18080"
    command:
      - start-history-server.sh
    environment:
      - SPARK_NO_DAEMONIZE=1
      - SPARK_PUBLIC_DNS=localhost
    networks:
      - spark-cluster
    volumes:
      - ./events:/tmp/spark-events

  jupyter-notebook:
    depends_on:
      - spark-master
    container_name: jupyter-notebook
    image: elopezdelara/miniconda3-spark:latest
    expose:
      - "4040"
      - "8888"
    ports:
      - "4040:4040"
      - "8888:8888"
    networks:
      - spark-cluster
    volumes:
      - ./notebooks:/opt/notebooks
      - ./events:/tmp/spark-events
    command:
      - jupyter
      - notebook
      - --ip='*'
      - --port=8888
      - --no-browser
      - --notebook-dir=/opt/notebooks
      - --allow-root
      - --NotebookApp.token=''

networks:
  spark-cluster:
    name: spark-cluster
